# Creating XMX-scanning.yml
name: XMX Scanning Action
on: [ push ]
jobs:
  build:
    name: XMX Scanning
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
       os: [ windows-latest ]
    steps:
      - uses: actions/checkout@v1
      - uses: ./dependency graph
        with:
          MY_NAME: "Arsyad07-ByArsyad06"
